version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/botevent-1.0.0.jar deploy/lib
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bot-event --output-template-file OutputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - deploy/lib/botevent-1.0.0.jar
    - OutputSamTemplate.yaml