AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Process Weather Event.
Resources:
  HelloLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.emirates.hackathon.botevent.BotEventHandler
      Runtime: java8
      CodeUri: deploy
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::663357122484:role/lambdaExecutionRole'
      Events:
              HelloLambdaApi:
                Type: Api
                Properties:
                  Path: /hello
                  Method: GET